szepeviktor/phpstan-wordpress

extension.neon
The ones that have `exit()` calls in them.
Fixes #22 
I'm not sure if the functions from the [utils.php](https://github.com/wp-cli/wp-cli/blob/master/php/utils.php) be included as well. Those are utility functions, not sure if they are used in userland code, or just for internal WP-CLI purposes.
=> Add WP-CLI early terminating calls

src/EscSqlDynamicFunctionReturnTypeExtension.php, src/StringOrArrayDynamicFunctionReturnTypeExtension.php
As `esc_sql()`, `wp_slash()` and `wp_unslash()` returns  `string|array`, but always the same type of the passed parameter.
=> Set return type of wp_slash() and wp_unslash().

extension.neon
This PR fixes the error:
`Service '0255': Class PHPStan\WordPress\EscSqlDynamicFunctionReturnTypeExtension not found. `
introduced in #34. When renaming the class name from `EscSqlDynamicFunctionReturnTypeExtension` to `StringOrArrayDynamicFunctionReturnTypeExtension`, I forgot to update the config file.
=> Fix wrong class name in extension.neon

extension.neon, src/ShortcodeAttsDynamicFunctionReturnTypeExtension.php
See https://developer.wordpress.org/reference/functions/shortcode_atts/
I had a case where I strictly specified a list of supported shortcode args and used `shortcode_atts` to filter what is "coming in" which PHPStan did not understand. Something like the following but more dynamic in a function
```php
/** @var array{foo: string, baz: ?string} */
$supportedArgs = [
'foo' => 'bar',
'baz' => null,
];
$args = shortcode_atts($supportedArgs, $userArgs);
// $args is still array{foo: string, baz: ?string} here independent of what keys are existing in $userArgs
```
=> Add dynamic return type extension for shortcode_atts

example/class-wp-nav-menu-args.php
Adds the `container_aria_label` argument which was added in WP 5.5.0.
=> Fix WP_Nav_Menu_Args

src/GetPostsDynamicFunctionReturnTypeExtension.php
When `get_posts()` is called and the `fields` argument is not included, the return type is `array<int,WP_Post>`.
=> Correct the default return type of `get_posts()`

extension.neon, src/MySQL2DateDynamicFunctionReturnTypeExtension.php
`mysql2date()` function returns:
* `false|int` when `$format` is `'G'` or `'U'`
* `false|string` otherwise
=> Add a return type extension for `mysql2date()`

extension.neon, src/GetObjectTaxonomiesDynamicFunctionReturnTypeExtension.php
`get_object_taxonomies()` function returns:
* `array<string,WP_Taxonomy>` when `$output` is `'objects'`
* `array<int,string>` otherwise
=> Add a dynamic return type extension for `get_object_taxonomies()`

src/GetPostsDynamicFunctionReturnTypeExtension.php
Using `id=>parent` returns `array<int,int>`, not `array<int,stdClass>`.
Refs:
* https://github.com/johnbillion/wordpress-develop/blob/b6046636f015f6e1fac6b565f883fa9679b90a72/src/wp-includes/class-wp-query.php#L655-L656
* https://github.com/johnbillion/wordpress-develop/blob/b6046636f015f6e1fac6b565f883fa9679b90a72/src/wp-includes/class-wp-query.php#L2965-L2982
=> Correct the return type for `get_posts()` with `id=>parent`

composer.json, phpstan.neon
I've fixed the level to 8 because max uses the new level 9 which results in some errors with `mixed` which can be addressed at a later date.
=> Switch to PHPStan v1

extension.neon, phpunit.xml.dist, src/ApplyFiltersDynamicFunctionReturnTypeExtension.php, tests/bootstrap.php, tests/data/apply_filters.php, tests/testTest.php
The return type of `apply_filters()` is indeterminate (therefore `mixed`). The return type is often wider than the type of the `$value` parameter being passed in, so it's not a generic function.
What we could do is introduce a dynamic function return type extension which reads the types from the docblock (if present) and treat those as the possible return types. This then places the burden on the developer to ensure the docblock is correct and subsequent code handles all possible return types.
Strictly, the only correct return type for `apply_filters()` is `mixed` because any filter can return a value of any type. In reality most code that uses `apply_filters()` assumes that it returns a value of the expected type. I need to give some more thought into whether treating the types in the …
=> `apply_filters()` return type

composer.json, phpcs.xml.dist, tests/DynamicReturnTypeExtensionTests.php, tests/bootstrap.php, tests/data/ApplyFiltersTestClass.php, tests/data/apply_filters.php, tests/data/current_time.php, tests/data/get_comment.php, tests/data/get_object_taxonomies.php, tests/data/get_post.php, tests/data/mysql2date.php, tests/functions.php
Related to or part of #75. To make things easier I'm planning to create one PR per tool.
To allow simpler automagic fixing, I converted the inline phpcs arguments into a phpcs.xml.dist config file and added a `test:cs:fix` script. Most of the simple changes here were done with that. I also ignored some rules for the tests completely as they do not make much sense there IMO or are not workig as expected (e.g. `NeutronStandard.Functions.TypeHint` complains about a missing return type hint if `iterable` is used).
Let me know what you think
=> Configure CS for tests

phpunit.xml.dist, tests/DynamicReturnTypeExtensionTest.php
Sorry, I broke them in #79 by renaming this file (phpunit did not execute those tests any more). This PR renames it again and removes the custom suffix config for phpunit. Unit tests should be running again now :)
=> Fix unit tests

example/phpstan-full.neon
The `@param` type for the `$deprecated` and `$plugin_rel_path` arguments of `load_plugin_textdomain()` have been corrected in WP 5.2.
See https://github.com/WordPress/wordpress-develop/blob/5.2/src/wp-includes/l10n.php#L760-L777 vs. https://github.com/WordPress/wordpress-develop/blob/5.1/src/wp-includes/l10n.php#L760-L776.
=> Comment out ignore rule for `load_plugin_textdomain()`

tests/data/apply_filters.php
Adds some test coverage for `apply_filters_ref_array()` and `apply_filters_deprecated()` which are also covered by the dynamic function return type extension. It's not comprehensive but it demonstrates that these functions are covered.
=> More tests for the return type of `apply_filters()` and related functions

composer.json, src/CurrentTimeDynamicFunctionReturnTypeExtension.php, src/GetCommentDynamicFunctionReturnTypeExtension.php, src/GetListTableDynamicFunctionReturnTypeExtension.php, src/GetObjectTaxonomiesDynamicFunctionReturnTypeExtension.php, src/GetPostDynamicFunctionReturnTypeExtension.php, src/GetPostsDynamicFunctionReturnTypeExtension.php, src/GetTaxonomiesDynamicFunctionReturnTypeExtension.php, src/IsWpErrorFunctionTypeSpecifyingExtension.php, src/MySQL2DateDynamicFunctionReturnTypeExtension.php, src/ShortcodeAttsDynamicFunctionReturnTypeExtension.php, src/StringOrArrayDynamicFunctionReturnTypeExtension.php
PHPStan >= 1.0 uses PHP Parser 4.13 which changed the handling of `Expr::$args`. This property should no longer be accessed directly; the `CallLike::getArgs()` method should be used instead. Release notes: https://github.com/nikic/PHP-Parser/releases/tag/v4.13.0
Here's where PHPStan made the change: https://github.com/phpstan/phpstan-src/commit/1c6ce5dfe4d16ad25ddef96a88541f7e44a3204f
The difference in behaviour is subtle and I only discovered it while working on #78. The `args` property is of type `array<Arg|VariadicPlaceholder>` but the return type of `CallLike::getArgs()` is `array<Arg>`. This means you can safely call methods on `Arg` that don't exist on `VariadicPlaceholder`.
=> Use the same version of PHP Parser that PHPStan uses

extension.neon, src/HookDocBlock.php, src/TermExistsDynamicFunctionReturnTypeExtension.php, tests/DynamicReturnTypeExtensionTest.php, tests/data/term_exists.php
The return type of `term_exists()` varies depending on its parameters. This adds a return type extension that covers this.
=> Add a dynamic function return type extension for `term_exists()`

extension.neon, src/GetTermsDynamicFunctionReturnTypeExtension.php, tests/DynamicReturnTypeExtensionTest.php, tests/data/get_terms.php
Introduces a dynamic return type extension for `get_terms()` and its wrapper functions. The `fields` and `count` arguments determine the return types.
Todo:
* `fields` argument set to:
* `count` argument set to:
* Confirm this definitely applies to:
=> Add return type definitions for `get_terms()`

extension.neon, src/HasFilterDynamicFunctionReturnTypeExtension.php, tests/DynamicReturnTypeExtensionTest.php, tests/data/has_filter.php
These functions return a boolean when `$callback` is false, otherwise an integer or false.
=> Introduce a dynamic return type extension for `has_filter()` and `has_action()`

extension.neon, src/EchoParameterDynamicFunctionReturnTypeExtension.php, tests/DynamicReturnTypeExtensionTest.php, tests/data/echo_parameter.php
These functions are [nearly] the worst. I've seen their non-existent return values used several times.
This covers all procedural functions with an `$echo` or `$display` parameter (all of which have a default value of `true`). There are some others which support an `$echo` argument inside an `$args` array, this doesn't cover those.
=> Introduce a dynamic return type extension for functions with an `$echo` or `$display` parameter

extension.neon, src/IsWpErrorRule.php, tests/IsWpErrorRuleTest.php, tests/data/is_wp_error.php
This introduces a rule that triggers an error when the type of the value passed to `is_wp_error()` can never be a `WP_Error` (or can only be a `WP_Error`). It prevents code from incorrectly checking something that can never be an error (eg. checking the return value of `wp_insert_post()` when the `$wp_error` parameter is false).
=> `is_wp_error()` rule

extension.neon
```
By dropping `%rootDir%` variable, including extension isn't strictly tied to path of PHPStan executable.
```
I would like to request a change in config file for this extension.
In my case, I would like to use PHPStan through `phar` file located in `tools` directory (default for installation from phive). Actually, it's possible, if I don't use `phpstan/extensions-installer` and rely on explicit include in my config file. (This also applies to globally installed phpstan executable).
Relying on relative path searches for wordpress-stubs package from current working directory instead of executable location, which is desired in aforementioned cases.
=> Use relative path in config file

composer.json
Since WordPress (and likewise `php-stubs/wordpress-stubs`) doesn't follow SemVer, I assume this one-liner is all that's necessary.
=> Add support for WP 6.0 stubs.

src/GetPostDynamicFunctionReturnTypeExtension.php, tests/data/get_post.php
This PR improves the dynamic return type extension for `get_post()` and `get_page_by_path()` by
1. removing `null` if the first argument `$post` is of type `WP_Post`,
2. dropping to return the default type hints in favor of always returning `WP_Post|null` as long as the second argument `$output` is not `ARRAY_A` or `ARRAY_N`.
Reasoning:
1. If `$post` is an instance of `WP_Post` the variable `_post` is set to `$post` (see [here](https://github.com/WordPress/WordPress/blob/87464289c387757943d07e8474d8dab61ba7b6f2/wp-includes/post.php#L995-L997)) and will never fail the existence check (see [here](https://github.com/WordPress/WordPress/blob/87464289c387757943d07e8474d8dab61ba7b6f2/wp-includes/post.php#L1010-L1012)) and hence will never be of type `null`.
2. Both `get_post()` and …
=> Improve dynamic return type extension for get_post()

composer.json, src/WpThemeGetDynamicMethodReturnTypeExtension.php, tests/data/_get_list_table.php, tests/data/get_comment.php, tests/data/get_object_taxonomies.php
Fixes the FQCN types by requiring PHPStan 1.8.7 where the behaviour was fixed causing a BC break here.
Refs: https://github.com/phpstan/phpstan/issues/8118
> Likely an **expected** side effect of this change https://github.com/phpstan/phpstan-src/pull/1758
Also if you check the changed tests files - each of them has other assertions where the backslash was missing, so this was already inconsistent and this is the best way to "fix" it here and move forward IMO.
=> Fix FQCN types

.travis.yml, composer.json, src/WpThemeGetDynamicMethodReturnTypeExtension.php
@herndlm Here we go 🐎 
From https://github.com/szepeviktor/phpstan-wordpress/pull/122#issuecomment-1309363724
=> Run tests on lowest deps also

extension.neon, src/AssertNotWpErrorTypeSpecifyingExtension.php, src/AssertWpErrorTypeSpecifyingExtension.php, tests/AssertMethodTypeSpecifyingExtensionTest.php, tests/data/assert_not_wp_error.php, tests/data/assert_wp_error.php
Might need a bit of help with the implementation & tests, but I think this should cover the basics.
Fixes #30
=> Add `AssertWpErrorTypeSpecifyingExtension` / `AssertNotWpErrorTypeSpecifyingExtension`

phpcs.xml.dist, src/AssertNotWpErrorTypeSpecifyingExtension.php, src/AssertWpErrorTypeSpecifyingExtension.php, tests/WP_UnitTestCase_Base.php, tests/data/assert_not_wp_error.php, tests/data/assert_wp_error.php
Viktor you were right, this was autoloader related. PHPStan needs to be able to cleanly autoload this class in order to fire the extensions. This is my first hacky approach to fix that autoloading with some kind of stub class copied into the tests folder.
The rest are just tiny fixes for the extensions themselves.
Refs: https://github.com/szepeviktor/phpstan-wordpress/pull/124 CC @swissspidy
=> Fix AssertWpErrorTypeSpecifying extensions

composer.json, src/HookCallbackRule.php, tests/HookCallbackRuleTest.php, tests/data/hook-callback.php
Fixes #125
Seems the problem is ultimately down to `mixed` return types.
=> Hook callback false positives for `mixed` return type

extension.neon, src/GetPermalinkDynamicFunctionReturnTypeExtension.php, tests/DynamicReturnTypeExtensionTest.php, tests/data/get_permalink.php
Adds dynamic function return type extension for `get_permalink()` and `get_the_permalink()`.
=> Add dynamic return type for `get_permalink()`/`get_the_permalink()`

src/CurrentTimeDynamicFunctionReturnTypeExtension.php, src/GetCommentDynamicFunctionReturnTypeExtension.php, src/GetListTableDynamicFunctionReturnTypeExtension.php, src/GetObjectTaxonomiesDynamicFunctionReturnTypeExtension.php, src/GetPermalinkDynamicFunctionReturnTypeExtension.php, src/MySQL2DateDynamicFunctionReturnTypeExtension.php, src/ShortcodeAttsDynamicFunctionReturnTypeExtension.php, src/StringOrArrayDynamicFunctionReturnTypeExtension.php, src/WpParseUrlFunctionDynamicReturnTypeExtension.php
Simplifies returning the default return type by replacing `return ParametersAcceptorSelector::selectFromArgs(...)->getReturnType();` with `return null;`.
=> Simplify returning default return type everywhere

src/GetPermalinkDynamicFunctionReturnTypeExtension.php, tests/data/get_permalink.php
Adds `get_post_permalink()` to `GetPermalinkDynamicFunctionReturnTypeExtension`
=> Add dynamic function return type for `get_post_permalink()`

extension.neon, src/EchoKeyDynamicFunctionReturnTypeExtension.php, tests/DynamicReturnTypeExtensionTest.php, tests/data/echo_key.php
This PR adds a dynamic return type extension covering the following functions that support an `$echo` argument inside an `$args` array with default value `true` or `1` :
* the_title_attribute()
* wp_dropdown_categories()
* wp_dropdown_languages()
* wp_dropdown_pages()
* wp_dropdown_users()
* wp_get_archives()
* wp_link_pages()
* wp_list_authors()
* wp_list_bookmarks()
* wp_list_categories()
* wp_list_comments()
* wp_list_pages()
* wp_list_users()
* wp_login_form()
* wp_page_menu()
=> Add return type extension for echo key in args array

composer.json, src/EchoKeyDynamicFunctionReturnTypeExtension.php, tests/data/echo_key.php
This PR addresses `EchoKeyDynamicFunctionReturnTypeExtension`. It
* adds return types for query string arguments,
* adds tests for `$args['echo']=0`, unknown values and function calls with query string,
* improves the logic of the helper methods.
=> Add return types for query strings to echo key extension

src/GetCommentDynamicFunctionReturnTypeExtension.php, tests/data/get_comment.php
This PR
* improves the dynamic return type extension for `get_comment()` by also checking the first argument and removing the null type if applicable,
* replaces the deprecated `$type instanceof ConstantStringType`,
* adds tests for the first argument being an instance of `WP_Comment` and for the no argument case.
=> Improve `get_comment()` return type extension

src/CurrentTimeDynamicFunctionReturnTypeExtension.php, src/GetListTableDynamicFunctionReturnTypeExtension.php, src/GetObjectTaxonomiesDynamicFunctionReturnTypeExtension.php, src/GetTaxonomiesDynamicFunctionReturnTypeExtension.php, src/MySQL2DateDynamicFunctionReturnTypeExtension.php, src/WpThemeGetDynamicMethodReturnTypeExtension.php
This PR replaces some of the deprecated `$type instanceof ConstantStringType` by
```php
if (count($type->getConstantStrings()) === 0) {}
foreach ($type->getConstantStrings() as $constantString) {}
```
as suggested in [Why Is instanceof *Type Wrong and Getting Deprecated?](https://phpstan.org/blog/why-is-instanceof-type-wrong-and-getting-deprecated).
Part of #149
=> Replace deprecated `$type instanceof ConstantStringType`

src/HasFilterDynamicFunctionReturnTypeExtension.php, tests/data/has_filter.php
This PR fixes the return type of `has_filter()` and `has_action()` for maybe false types.
A maybe false type such as `callable|string|array|false` is not an instance of MixedType in 
https://github.com/szepeviktor/phpstan-wordpress/blob/5c6c6c47b77251ba2c0753c3ff8842cb08190f9e/src/HasFilterDynamicFunctionReturnTypeExtension.php#L42-L47
Failing test:
```php
// Maybe false callback
/** @var callable|string|array|false $callback */
$callback = $_GET['callback'];
assertType('bool|int', has_filter('', $callback));
assertType('bool|int', has_action('', $callback));
```
This PR also replaces a deprecated `instanceof ConstantBooleanType`.
=> Fix dynamic return type extension for `has_filter()`/`has_action()`

src/TermExistsDynamicFunctionReturnTypeExtension.php, tests/data/term_exists.php
This PR fixes the return type of term_exists() for an integer type first parameter with unknown value. An unknown value can be `0` for which `term_exists()` returns 0. This PR also replaces the deprecated `$type instanceof ConstantIntegerType`.
=> Fix dynamic return type extension for `term_exists()`

src/IsWpErrorRule.php
Fixes "Exception WP_Error should be referenced via a fully qualified name." related to coding standards.
=> Fix 'WP_Error should be referenced via a fully qualified name.'

composer.json, src/GetSitesDynamicFunctionReturnTypeExtension.php, tests/data/get_sites.php
This PR
* fixes the dynamic function return type extension for `get_sites()`,
* adds correct tests,
* bumps the required minimum version of PHPStan to 1.10.0 (needed for `Type::getConstantScalarValues()`),
* removes deprecated `instanceof`.
What has been fixed?
* There is no `$args['fields'] = 'count'` but `$args['fields'] = 'ids'` and `$args['count']`. The extension now checks for both `$args['fields]` and `$args['count']`. Not properly checking for 'count' led to incorrect return types for truthy count types.
* A return type for indetermined argument type has been added.
Todo:
* Adding tests for string parameter.
=> Fix dynamic function return type extension for `get_sites()`

tests/data/get_sites.php
This PR adds tests for `get_sites()`
* with string parameter,
* with explicit empty parameter.
=> Add tests for `get_sites()`

src/GetSitesDynamicFunctionReturnTypeExtension.php
Refactors the dynamic function return type extension for `get_sites()` to improve readability.
Last PR addressing this extension :innocent:
=> Refactor get_sites() extension to improve readability

src/GetSitesDynamicFunctionReturnTypeExtension.php
This PR removes duplicate values from the `$fields` and `$count` array as the `count($this->count)` and `count($this->fields)` logic relies on unique values. This ensures that statements like `count($this->count) === 1` are `true` even if there are two or more constant arrays with `$args['count'] = true`.
=> GetSites extension: Remove duplicate values from array

src/EchoKeyDynamicFunctionReturnTypeExtension.php, tests/data/echo_key.php
Closes https://github.com/szepeviktor/phpstan-wordpress/issues/160
@IanDelMar check out the first one, we don't even have to care if it's a constant array or not :)
the second one feels a bit like an overkill, but it is more correct I guess..
=> Improve echo type handling in EchoKey extension

src/StringOrArrayDynamicFunctionReturnTypeExtension.php
Types outdated since WP 5.5.0
Related to #154
=> Remove return types for `wp_slash()` and `wp_unslash()`

extension.neon
This list is potentially endless, but here are two more constants that I've had to add to the `dynamicConstantNames` list in my own plugins.
=> Add some more dynamic constants

bootstrap.php, extension.neon
See: https://github.com/WordPress/wordpress-develop/blob/e30ce9d4b57a38e7d7fe8c0665c71e444943c555/src/wp-includes/default-constants.php#L104-L114
=> Add SCRIPT_DEBUG as dynamic constant

bootstrap.php
See [`wp_templating_constants()`](https://github.com/WordPress/wordpress-develop/blob/dbbc9bcf98787fd77fd920df84cc9bbc69974b0a/src/wp-includes/default-constants.php#L387-L420)
=> Add TEMPLATEPATH, STYLESHEETPATH, and WP_DEFAULT_THEME constants

src/WpParseUrlFunctionDynamicReturnTypeExtension.php, tests/data/wp_parse_url.php
=> Remove deprecated `instanceof` from `wp_parse_url` extension

extension.neon
Not sure if that was a change with recent PHPStan versions or always incorrect, but these only work when I follow the syntax example from https://phpstan.org/writing-php-code/solving-undefined-variables
=> Fix earlyTerminatingMethodCalls syntax

src/GetPostsDynamicFunctionReturnTypeExtension.php, tests/data/get_posts.php
What I was wondering when updating this extension. I can have a non constant array that has a key `'fields'`.
```php
// Non constant array with fields first
$array = [
'fields' => 'ids',
$_GET['foo'] => $_GET['bar'],
];
assertType('array<int, int|WP_Post>', get_posts($array));
// Non constant array with fields last
$array = [
$_GET['foo'] => $_GET['bar'],
'fields' => 'ids',
];
assertType('array<int, int>', get_posts($array));
```
`get_post($array)` with the fields first case returns `array<int, int|WP_Post>` because `$_GET['foo']` may be `'fields'` and overwrite `'ids'`. `get_post($array)` with the fields last case returns  `array<int, int>` as `'fields'` is not affected by `$_GET['foo']` and hence will  be `'ids'`. With limited PHPStan knowledge, I was not able to find a way to check the …
=> Remove deprecated `instanceof`

src/GetListTableDynamicFunctionReturnTypeExtension.php, tests/data/_get_list_table.php
Fixes the dynamic return type extension for `_get_list_table()`.
According to the [docs](https://developer.wordpress.org/reference/functions/_get_list_table/), `_get_list_table()` returns a (known or unknown) child class of WP_List_Table or WP_List_Table class itself if the passed argument is a WP_List_Table (child) class name, and `false` otherwise.
As the class name is filterable any WP_List_Table child class maybe returned... We can either assume that in most cases this filtered is not used and return a `WP_Posts_List_Table` when the argument is `WP_Posts_List_Table` and risk that this is incorrect (the previous functionality and the current approach) or we can simply return a `WP_List_Table` which will be correct but less precise.
=> Fix _get_list_table extension

tests/data/mysql2date.php
Drops tests for unsupported types as PHPStan warns about the incorrect parameter types.
=> Remove unnecessary tests for mysql2date extension

composer.json, src/WpDieDynamicFunctionReturnTypeExtension.php, tests/data/wp_die.php
Fixes #203
Adds missing tests (https://github.com/szepeviktor/phpstan-wordpress/issues/203#issuecomment-1764619896)
=> Fix dynamic return type extension for `wp_die()`

tests/AssertMethodTypeSpecifyingExtensionTest.php, tests/DynamicReturnTypeExtensionTest.php
The `\PHPStan\Testing\TypeInferenceTestCase::gatherAssertTypes()` method is called statically. See the implementation in the PHPStan source code here: [PHPStan TypeInferenceTestCase.php line 118-120](https://github.com/phpstan/phpstan-src/blob/6bdc25a944690839507a8ca96d33ec7c51660f3f/src/Testing/TypeInferenceTestCase.php#L118-L120).
We have updated the minimum required version from 1.10.0 to 1.10.31. In version 1.10.0, it was still called dynamically, as can be seen here: [PHPStan TypeInferenceTestCase.php line 81-83](https://github.com/phpstan/phpstan-src/blob/2ca979344d7750dee065ffb6c43af6236f398241/src/Testing/TypeInferenceTestCase.php#L81-L83)."
=> Fix dynamic call to static method

extension.neon, src/GetApprovedCommentsDynamicFunctionReturnTypeExtension.php, tests/DynamicReturnTypeExtensionTest.php, tests/data/get_approved_comments.php
`get_approved_comments` changes the return type based on value within the passed $args parameter.
- Return 'WP_Comment[]' by default.
- Return `int[]` if `$fields = 'ids'`.
- Return `int` if `$count = true`.
https://developer.wordpress.org/reference/functions/get_approved_comments/#return
=> Introduce dynamic return type for the `get_approved_comments` function

bootstrap.php
Defined in `wp_set_lang_dir()`.
There is no function to read this constant.
Related:
* #193
=> Add WP_LANG_DIR constant

bootstrap.php
There is no core function to read this constant. Core reads the constant directly.
See https://github.com/szepeviktor/phpstan-wordpress/pull/212#issuecomment-1994556934
=> Add WP_CONTENT_DIR constant

bootstrap.php, extension.neon
As with the `WP_DEBUG` constant, there is no function to read the [`WP_DEBUG_DISPLAY`](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/#wp_debug_display) constant. Core looks at the constant directly.
=> Add WP_DEBUG_DISPLAY constant

src/WpParseUrlFunctionDynamicReturnTypeExtension.php, tests/data/wp_parse_url.php
This update to `WpParseUrlFunctionDynamicReturnTypeExtension` from [PHPStan's extension for `parse_url`](https://github.com/phpstan/phpstan-src/blob/877ff0a620dc407182e71955fbde8b6e081a15ce/src/Type/Php/ParseUrlFunctionDynamicReturnTypeExtension.php) fixes an incorrect return type when the `$component` parameter is a non-constant integer. Additionally, the extension is now more specific about the port type.
=> Fix/update extension for wp_parse_url

bootstrap.php
These constants were added in WP 6.0.0:
- PB_IN_BYTES
- EB_IN_BYTES
- ZB_IN_BYTES
- YB_IN_BYTES
=> Add data size constants

src/EchoKeyDynamicFunctionReturnTypeExtension.php, tests/data/echo_key.php
As documented, `wp_dropdown_categories()` always returns a string. See [lines 481-485 in wp-includes/category-template.php](https://github.com/WordPress/WordPress/blob/e25ffd14269ad6461aba63e3119ac5603502bf06/wp-includes/category-template.php#L481-L485).
=> Remove return type extension for wp_dropdown_categories

src/EchoKeyDynamicFunctionReturnTypeExtension.php, tests/data/echo_key.php
Whether `wp_dropdown_languages()` return string or void does not depend on `$args['echo']` but on `$args['id']` and `$args['name']`. See lines [1678-1680](https://github.com/WordPress/WordPress/blob/e25ffd14269ad6461aba63e3119ac5603502bf06/wp-includes/l10n.php#L1678-L1680) and [1780-1784](https://github.com/WordPress/WordPress/blob/e25ffd14269ad6461aba63e3119ac5603502bf06/wp-includes/l10n.php#L1780-L1784) in wp-includes/l10n.php.
=> Remove return type extension for wp_dropdown_languages

src/ApplyFiltersDynamicFunctionReturnTypeExtension.php, src/AssertNotWpErrorTypeSpecifyingExtension.php, src/AssertWpErrorTypeSpecifyingExtension.php, src/HookCallbackRule.php, src/HookDocBlock.php, src/HookDocsRule.php, src/HookDocsVisitor.php, src/WpParseUrlFunctionDynamicReturnTypeExtension.php
v2 requires PHP 7.4, so we can now add type declarations to properties.
=> Add type declarations to properties
