szepeviktor/phpstan-wordpress

composer.json

Enable PHPStan Extension installer to autoload this extension

Define package as PHPStan Extension

---

extension.neon

First we need https://github.com/phpstan/phpstan/pull/2392

Recognize wp_die as earlyTerminatingFunction

---

README.md

I created a new PHPStan website with full-fledged documentation, so I'd like all links to reflect this :) Thanks.

Updated README with link to new PHPStan website

---

extension.neon

This is how you get rid of the error. Please release this. Thanks.

Fix the deprecation notice

---

extension.neon

These functions and methods all unconditionally terminate.

Define more functions that unconditionally terminate

---

src/GetCommentDynamicFunctionReturnTypeExtension.php
src/GetPostsDynamicFunctionReturnTypeExtension.php
src/GetTaxonomiesDynamicFunctionReturnTypeExtension.php

Docs corrections

---

composer.json
extension.neon
src/Composer/FixWpStubs.php
src/GetCommentDynamicFunctionReturnTypeExtension.php
src/GetPostDynamicFunctionReturnTypeExtension.php
src/GetPostsDynamicFunctionReturnTypeExtension.php
src/GetTaxonomiesDynamicFunctionReturnTypeExtension.php
src/IsWpErrorFunctionTypeSpecifyingExtension.php
src/RedirectCanonicalDynamicFunctionReturnTypeExtension.php
src/ShortcodeAttsDynamicFunctionReturnTypeExtension.php
src/StringOrArrayDynamicFunctionReturnTypeExtension.php
src/WpThemeMagicPropertiesClassReflectionExtension.php

Tested manually via Composer VCS require
Fixes #45

Fix phpstan problems

---

src/ShortcodeAttsDynamicFunctionReturnTypeExtension.php

Types were only inferred from the default attributes. This adds the string shortcode attributes as union values.
E.g.
```php
$atts = shortcode_atts(['foo' => null, 'bar' => 17], ['foo' => 'baz']);
```
resulted in `array('foo' => null, 'bar' => int)` previously while it now correctly results in `array('foo' => string|null, 'bar' => string|int)`
I was not a 100% sure about the implementation but apparently Ondrej approves ;) https://github.com/phpstan/phpstan/discussions/5303

Fix shortcode_atts extension

---

example/class-wp-post-meta-row.php

To be consistent with the other example files.

Remove empty line before file header in example file

---

tests/data/_get_list_table.php
tests/data/get_comment.php
tests/data/get_post.php

@johnbillion The previous PR #75 showed that we need to add some dollar signs.
Could you comment on the rest of the errors?
https://app.travis-ci.com/github/szepeviktor/phpstan-wordpress/jobs/547712634#L469

Fix _GET superglobal

---

README.md

It's not easy to explain this. Hopefully this is good enough.

Docs for the `apply_filters()` handling

---

tests/DynamicReturnTypeExtensionTest.php
tests/data/shortcode_atts.php

This thing is complex and debattable if it is correct enough, but I wanted to add some tests for the current state at least

Add shortcode_atts tests

---

phpstan.neon
src/Composer/FixWpStubs.php

Not entirely sure if and where `FixWpStubs` is used though. Is it still needed?

PHPStan level 9

---

example/class-wp-nav-menu-args-stdclass.php
example/class-wp-nav-menu-item-wp-post.php

Add nav menu classes with "extends"

---

extension.neon
src/WpThemeGetDynamicMethodReturnTypeExtension.php
tests/DynamicReturnTypeExtensionTest.php
tests/data/wp_theme_get.php

This PR adds a dynamic return type extension for the get method of WP_Theme.

Add dynamic return type extension for WP_Theme::get()

---

src/EchoParameterDynamicFunctionReturnTypeExtension.php
src/GetPermalinkDynamicFunctionReturnTypeExtension.php
src/GetPostDynamicFunctionReturnTypeExtension.php
src/IsWpErrorRule.php
src/ShortcodeAttsDynamicFunctionReturnTypeExtension.php
src/WPErrorParameterDynamicFunctionReturnTypeExtension.php

Part of https://github.com/szepeviktor/phpstan-wordpress/issues/149

Remove deprecated `instanceof`

---

src/StringOrArrayDynamicFunctionReturnTypeExtension.php

Simplify StringOrArrayDynamicFunctionReturnTypeExtension

---

README.md

👀
https://github.com/szepeviktor/phpstan-wordpress/blob/szepeviktor-patch-1/README.md#support-my-work
@adamlaki There seems to be a color difference and this heart does not beat :(
What if we add the same ids/classes -> then GitHub's CSS will work on our svg too?

Add Support my work section

---

tests/data/current_time.php

Remove unnecessary tests for current_time extension

---

bootstrap.php

Add WP_PLUGIN_DIR constant

---

composer.json

Fix supported core stubs version

---

extension.neon
src/WpDieDynamicFunctionReturnTypeExtension.php
tests/DynamicReturnTypeExtensionTest.php
tests/data/wp_die.php

Add dynamic return type extension for `wp_die()`

---

tests/data/get_comment.php
tests/data/get_object_taxonomies.php

Synchronize with new stubs

---

composer.json

From https://github.com/szepeviktor/phpstan-wordpress/pull/227#issuecomment-2197450983

raise phpstan constraint

---

tests/data/_get_list_table.php
tests/data/echo_key.php

See https://github.com/szepeviktor/phpstan-wordpress/pull/243#issuecomment-2403858688

Remove some tests with invalid argument type

---

composer.json

Support for PHP 7.2 has been removed

Remove symfony/polyfill-php73
